src/og.py
Currently, the default language for translate is automatically set to 'en'. If a user uses a document with languages other than English, the "--translate" option won't work
Change the default translate option to 'auto' instead of 'en' so that the Textract automatically identifies the document's default language for translation
=> Update og.py for translate fix 

src/trp.py
The code to determine reading order is using a faulty bounding box overlap test. 
Compute the midpoint of the left and right bounds.
=> Typo: Calculate column center correctly

helper/README.md, helper/bin/amazon-textract
Now can use --stdin for input in addition to --example and --input-document. Useful when piping JSON 
=> adding stdin to command line tool

textractor/visualizers/entitylist.py
remove extra indent that causes with_text=True to return None
=> Fix bug in visualization

textractor/data/constants.py, textractor/visualizers/entitylist.py
*Issue #, if available:  #112*
*Description of changes: Adds Query Result to visualizer output*
```
python3 textractor/cli/cli.py analyze-document tests/fixtures/form.png output.json \
--features QUERIES \
--queries 'What is the age of John Doe?' \
'What is John Doe social security number?'
'Who is John Doe spouse?'
'What is John Doe home address?'
'What is John Doe e-mail address?'
--overlay QUERIES
--font-size-ratio 1.1
```
Couple thing that I wish to address in a different PR:
- Text clips outside of the page, we should enforce bounds checking to prevent it from happening.
- Text is hard to read as it overlaps on existing text. 
=> Add query to visualizer output

textractor/textractor.py
*Issue #, if available:* Fixes #121
*Description of changes:* Remove `call_mode` from the expense API call as it is not needed anyway. Improve message regarding missing pdf2image dependency to point users towards `save_image=True`.
=> Fix start_analyze_expense raising exception

extras/dev.txt, extras/docs.txt, requirements.txt, textractor/utils/search_utils.py
*Issue #, if available:* Removes pyxDamerauLevenshtein and replace it with `editdistance` as the latter comes with pre-built wheels that are compatible with more environments.
*Description of changes:* Replaces pyxDamerauLevenshtein with `editdistance`.
=> Use editdistance instead of pyxDamerauLevenshtein

textractor/entities/table.py
*Description of changes:* XlsxWriter version 3.0.6 raises an exception on merging overlapping cells. To anyone experiencing this issue downgrading to 3.04 will fix it. This PR fixes the underlying issue and only adds merged cells to the workbook once.
=> Fix XlsxWriter raising an exception on overlapping merged cells

textractor/parsers/response_parser.py
#146
Added logic that will ignore the `SIGNATURE` element when building Value Object for Key-Value Sets.
=> fix: ignore elements with SIGNATURE BlockType when building Value Objects

textractor/textractor.py
*Description of changes:* Update the documentation to remove the mention of List[PIL.Image] as a supported file_source for the async APIs.
=> Remove line implying that async APIs take List[PIL.Image] as file_source

caller/textractcaller/__init__.py, caller/textractcaller/t_call.py
fixes #207
When using OutputConfig the files where sorted alphabetically, not numerically and lead to not ordered full JSON output.
=> fix: ordering of paginated files on S3 OutputConfig

textractor/parsers/response_parser.py
*Issue #, if available:* None
*Description of changes:* This addresses an issue caused by `QUERY_RESULT` blocks sometimes not having a grounding bounding box which raises and exception. We address it by using the entire page as the default bounding box. 
=> Fix empty bounding box in QUERY_RESULT block raising exception

textractor/entities/expense_field.py, textractor/parsers/response_parser.py
*Issue #, if available:* #195
*Description of changes:* Allow creation of value `Expense` without bounding box and update `ExpenseField` to support values without a bounding box. 
=> Fix missing bounding box for empty values

tpipelinegeofinder/textractgeofinder/tgeofinder.py
*Issue #, if available:* 160 - https://github.com/aws-samples/amazon-textract-textractor/issues/160
Calling the get_words_below() function yields the following error:
```
Traceback (most recent call last):
File "c:\Users\User\Desktop\turnco\_geofinder_test.py", line 129, in <module>
words = geofinder_doc.get_words_below(
File "C:\Python39\lib\site-packages\textractgeofinder\tgeofinder.py", line 269, in get_words_below
return self.ocrdb.execute(query=query,
File "C:\Python39\lib\site-packages\textractgeofinder\ocrdb.py", line 171, in execute
return [TWord(ocrdb_row=x) for x in cursor.execute(query_composed, params_composed)]
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 6, and there are 5 supplied.
```
The problem is …
=> add ymax param in get_words_below query

textractor/parsers/response_parser.py
*Issue #, if available:* 
Fixes https://github.com/aws-samples/amazon-textract-textractor/issues/216
Continue if the line_item_rows is empty or None, this avoids the assertion error raised when called the subsequent line to create Groups
=> Fix assertion error on empty line item rows

textractor/textractor.py
*Issue #, if available:* #226
*Description of changes:* Adds type condition in two async function to ensure that the `file_source` is str before using `.startswith()` on it.
=> Add type check before S3 prefix check

textractor/entities/bbox.py, textractor/parsers/response_parser.py
*Description of changes:* Comment out denormalization with parent spatial object as it does not make sense with the API output. Also fixes table titles and table footers that are not created with a spatial object.
=> Fix bbox denormalization breaking visualizations

textractor/textractor.py
In cases the pdf-filename is uppercase like document.PDF an error is raised. This commit fixes it
My document filename is document.PDF, this raises an error
Endswith-comparison is made between filenamestring.lower() and ".pdf"
=> Fix for PDF-filename suffix is hardcoded as .pdf

textractor/entities/expense_field.py
When the `label` is None, and `value.bbox` is also None, we cannot create an `ExpenseField` enclosing_bbox.
By checking the `value.bbox` before accessing `value.bbox.spatial_object`, we can avoid this error.
```
enclosing_bbox = None
if label:
enclosing_bbox = BoundingBox.enclosing_bbox([label.bbox, value.bbox], spatial_object=label.bbox.spatial_object)
elif value.bbox:
enclosing_bbox = BoundingBox.enclosing_bbox([label, value], spatial_object=value.bbox.spatial_object)
```
Here is a sample you can use to recreate the issue
=> Fix ExpenseField value.bbox is None causing Error

tests/test_document.py, textractor/entities/document.py, textractor/utils/search_utils.py
*Description of changes:* The normalized levenshtein distance did not work and returned the most dissimilar item from the KV dictionary. 
=> Fix Levenshtein distance not returning the most similar key

prettyprinter/README.md, prettyprinter/textractprettyprinter/t_pretty_print.py, prettyprinter/textractprettyprinter/t_pretty_print_layout.py
*Prettyprinter support for LAYOUT:*
Get linearized text from LAYOUT using get_text_from_layout_json method
Generates a dictionary of linearized text from the Textract JSON response with LAYOUT, and optionally writes linearized plain text files to local file system or Amazon S3. It can take either per page JSON from AnalyzeDocument API, or a single combined JSON with all the pages created from StartDocumentAnalysis output JSONs.
=> Layout linearizer 01

textractor/entities/table.py
*Issue #, if available:* #255
*Description of changes:* Replace logging.info by raise Exception when exporting tables to markdown without pandas installed, replacing:
```py
File "/belval/textractor/entities/table.py", line 602, in get_text_and_words
has_column = any([isinstance(c, str) for c in df.columns])
^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
```
by
```py
File "/belval/textractor/entities/table.py", line 594, in get_text_and_words
df = self.to_pandas(
^^^^^^^^^^^^^^^
File "/belval/textractor/entities/table.py", line 475, in to_pandas
raise MissingDependencyException(
textractor.exceptions.MissingDependencyException: pandas library is required for exporting tables to DataFrame objects/markdown
```
Ideally we should support table to markdown without …
=> Raise exception on export-to-markdown without pandas

textractor/data/text_linearization_config.py, textractor/entities/layout.py
*Description of changes:* Adds configuration option to add a prefix or a suffix to page number in linearized documents. Useful for GenAI usecases.
=> Add page number prefix and suffix to linearization config

textractor/entities/lazy_document.py, textractor/textractor.py, textractor/utils/results_utils.py
*Description of changes:* With this change, when provided with an S3 bucket and prefix (OutputConfig) the GetResult function in LazyDocument will query the S3 output path instead the Textract service. This scales significantly better as Textract GetResult has a base TPS that is 2 orders of magnitudes lower than S3 which caused exceptions when used at scale. 
=> Add GetResult from S3 in LazyDocument

requirements.txt
In attempting to use this project as a dependency, I noticed it specifies an older version constraint for `XlsxWriter` (`<3.1`) which conflicts with my project's requirements. In investigating the `XlsxWriter` [release notes](https://xlsxwriter.readthedocs.io/changes.html#release-3-1-0-april-13-2023), it appears that 3.1 is just a minor release (no obvious breaking changes) so I think we can loosen the constraints here.
I ran the test suite locally with the latest version of `XlsxWriter` (3.1.9) and all the tests passed (which I put at least some stock in because I see `.to_excel()` calls in the test suite, which I know are being called).
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> Loosen XlsxWriter version constraints

textractor/parsers/response_parser.py
*Description of changes:* Due to duplicate suppression, some lines were getting their words removed, causing `page.lines` to report empty lines.
=> Fix missing lines in page

prettyprinter/textractprettyprinter/t_pretty_print_layout.py
*Issue #, if available:* #291
*Description of changes:* Page number comparison when linearizing Tables with multi-page documents was missing. Added a page compare.
=> Fix for #291 - Markdown issue with Tables in multi-page documents

textractor/utils/s3_utils.py
This PR addresses an issue with the `textractor.utils.s3_utils.download_from_s3` function where the BytesIO buffer is not reset to the 0 position before returning. As a result, downstream callers encounter a `json.decoder.JSONDecodeError`
This fix simply resets the position of the BytesIO buffer, with `f.seek(0)`
=> fix: resets BytesIO buffer to 0 position

textractor/entities/query.py, textractor/entities/query_result.py
*Issue #, if available:* #327
*Description of changes:* Fix `.get_text()` on Query object. Words will still be an empty list has QueryResults don't have words.
=> Return query and query answer with get_text()

textractor/visualizers/entitylist.py
*Description of changes:* Convert PIL images to RGB before returning in `.visualize()` as a RGBA image will cause an error. 
=> Convert image to RGB in EntityList for Jupyter compatibility

textractor/parsers/response_parser.py
*Description of changes:* Fixes an issue where the Query response bbox will be null instead of absent causing the code to not default to the full-page bbox, which itself raises an exception. 
=> Handle None bounding box when parsing Queries

textractor/textractor.py
*Issue #, if available:* #341
*Description of changes:* Set JPEG compression quality to 95 and subsampling to 0 (4:4:4) as the default apply too much compression which degrades Textract performance compared to calling boto3 directly.
Originally the idea was to make it lossless: https://github.com/aws-samples/amazon-textract-textractor/tree/use-png-in-file-manipulations however there is a significant latency hit from doing so (~200ms) so it will be done in a future update as an option instead of a widespread change.
=> Set JPEG compression parameters

textractor/cli/cli.py, textractor/textractor.py
*Issue #, if available:* #352
*Description of changes:* This change checks if the `AWS_REGION` or `AWS_DEFAULT_REGION` environment variable is available before defaulting to the default profile. Following the `awscli` implementation, the former takes precedence over the latter. This improve user experience in managed environments such as SageMaker notebooks.
=> Use AWS_REGION  and AWS_DEFAULT_REGION environment variables in Textractor when available

prettyprinter/textractprettyprinter/t_pretty_print_layout.py
Table elements without a text element will cause pretty printing to fail.
=> ensure cell block has text element

tests/test_document.py, textractor/entities/document_entity.py, textractor/entities/expense_field.py, textractor/entities/key_value.py, textractor/entities/layout.py, textractor/entities/line.py, textractor/entities/query_result.py, textractor/entities/selection_element.py, textractor/entities/signature.py, textractor/entities/table_cell.py, textractor/entities/value.py, textractor/entities/word.py
*Description of changes:* This change makes `confidence` available at the `DocumentEntity` level, meaning that most component will now have `.confidence` and the field will be populated using the `raw_object` property.
=> Add confidence scores at the DocumentEntity level

caller/textractcaller/t_call.py
*Description of changes:* Removes the restriction that caused `call_textract` to fail if called with a file with a .pdf extension. 
=> Allow PDF in for DetectDocumentText and AnalyzeDocument

.github/workflows/lambda_layers.yml, extras/pdfium.txt, textractor/exceptions.py, textractor/textractor.py, textractor/utils/pdf_utils.py
*Description of changes:* Probably one of the most requested feature, with this change Textractor will support PDF rasterization with `pypdfium2` which is simpler to install than `pdf2image`. For backward compatibility both will be supported for the foreseeable future. Additionally, removes the PDF page count check in the synchronous functions and simply catch the exception if a multipage PDF is sent to the wrong API.
=> Use pypdfium2 for PDF rasterizing when possible

textractor/exceptions.py, textractor/textractor.py
*Issue #, if available:* #364 
*Description of changes:* This removes `RegionMismatchError` and replaces it with `InvalidS3ObjectException`. Additionally the exception explanation makes it clear to check the S3 path first and then to check for region mismatch.
=> Replace region mismatch with invalid S3 object

textractor/entities/table.py
*Issue #, if available:* #380
*Description of changes:* Bug introduces in 1.8.0 that tries to use `local_config` even though the variable only exists in the plaintext/html linearization path.
=> Fix .to_markdown() raising an exception on missing local config

textractor/data/html_linearization_config.py, textractor/entities/key_value.py, textractor/entities/layout.py, textractor/entities/table.py, textractor/entities/value.py, textractor/parsers/response_parser.py, textractor/utils/html_utils.py
*Description of changes:* This change adds a toggle allowing users to include the layout element ids to the HTML output. This allows for further post-processing as needed. 
To avoid impacting LLM token counts, we also offer truncated uuids (8 characters).
=> Id in html output

textractor/data/html_linearization_config.py, textractor/entities/key_value.py, textractor/entities/layout.py, textractor/entities/line.py, textractor/entities/table.py, textractor/entities/value.py, textractor/entities/word.py, textractor/parsers/response_parser.py, textractor/utils/html_utils.py
*Description of changes:* Addresses an issue where words containing &, < or > would break `lxml` parsing of the output. 
=> Escape html output

textractor/textractor.py
N/A
Fixed a typo where the 'queries' type hint was being marked as the 'features' type hint in textractor.textractor.analyze_document().
=> Update analyze_document type hint

textractor/entities/document.py
**Description of Changes:**
The `export_kv_to_csv` function currently uses a hard-coded semicolon (`;`) as a separator, which can cause issues when key-value pairs contain this character. This PR introduces a parameterized approach, allowing users to define their own unique and valid separator, addressing issues caused by multiple semicolons in a single line. By enabling customizable separators, we ensure consistent parsing of key-value data, regardless of the content.
**Details of Changes:**
- Added `sep` as a configurable parameter, allowing users to specify any unique separator character(s).
- Updated documentation to reflect the flexibility in separator choice.
- Improved handling to prevent separator conflicts in CSV outputs by allowing for unique symbol combinations, reducing …
=> Allow Custom Separator in `Document.export_kv_to_csv()`

textractor/entities/expense_field.py, textractor/visualizers/entitylist.py
*Issue #, if available:* #401
*Description of changes:* Adds a check to gracefully handle expense with type OTHER that are missing bounding boxes.
=> Add check for None bounding boxes for AnalyzeExpense

textractor/entities/bbox.py
The BoundingBox docstring uses some latex style `\in`, but python sees the `\i` as an invalid escape and issues a SyntaxWarning:
```
$ python -Werror -c 'import textractor'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/app/amazon-textract-textractor/textractor/__init__.py", line 3, in <module>
from .textractor import Textractor
File "/app/amazon-textract-textractor/textractor/textractor.py", line 53, in <module>
from textractor.entities.document import Document
File "/app/amazon-textract-textractor/textractor/entities/document.py", line 17, in <module>
from textractor.entities.expense_document import ExpenseDocument
File "/app/amazon-textract-textractor/textractor/entities/expense_document.py", line 11, in <module>
from textractor.entities.expense_field …
```
=> Fix invalid escape in BoundingBox docstring

.github/workflows/documentation.yml, .github/workflows/tests.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> ci: Use GITHUB_OUTPUT envvar instead of set-output command

textractor/entities/page.py, textractor/parsers/response_parser.py
*Issue #, if available:* #388
*Description of changes:* Update the table layout element creation logic to split larger layouts when the split can be done without ambiguity.
Before:
```
Page 2 of 10
Schneider Electric South East Asia (HQ) Pte. Ltd. Schneider Electric Overseas Asia Pte Ltd Schneider Electric Singapore Pte. Ltd. Schneider Electric IT Singapore Pte. Ltd. (formerly known as MGE Asia Pte Ltd) Schneider Electric IT Logistics Asia Pacific Pte. Ltd. Schneider Electric Logistics Asia Pte Ltd Schneider Electric Systems Singapore Pte. Ltd. (formerly known as Invensys Process Systems (S) Pte. Ltd.) 1 March 2017 
Previous Facility Letters. In the event that this Facility Letter is not accepted or lapses and is not extended by the Bank, the terms and conditions in the Previous Facility …
```
=> Add function to split larger element at table insertion

textractor/entities/page.py
adding an optional sep argument to the export_kv_to_csv function
=> add sep to kv_to_csv

textractor/entities/document.py
**Description of Changes**:
The `export_kv_to_pandas` function is a new addition that converts key-value pairs with optional confidence filtering into a pandas DataFrame. I find myself needing to use this quite a lot. This PR introduces a safe import check for the `pandas` library, ensuring that the function only runs if `pandas` is available, thus improving error handling. Additionally, we have added configurable options for confidence filtering, trimming whitespace and punctuation, and optional inclusion of the confidence score.
**Details of Changes**:
- **Safe Import Check**: 
- Added an inline import check for `pandas.DataFrame`. If `pandas` is not installed, a `MissingDependencyException` is raised with a clear message: `"pandas library is required for exporting tables to DataFrame …
=> new feature: export_kv_to_pandas

textractor/entities/document.py, textractor/entities/expense_field.py, textractor/entities/identity_document.py, textractor/entities/key_value.py, textractor/entities/page.py, textractor/entities/signature.py, textractor/entities/table.py, textractor/parsers/response_parser.py, textractor/textractor.py, textractor/utils/legacy_utils.py
*Issue #, if available:* #367
*Description of changes:* Replace `logging.` usages with module-level `logger.`.
=> Replace logging calls with module logger

textractor/entities/layout.py, textractor/parsers/response_parser.py
*Issue #, if available:* #424
*Description of changes:* Fix exception raised during linearization if one of the LAYOUT_LIST child does not have a reading_order. Additionally, ignore KV for linearization if they fall within a LAYOUT_LIST element.
=> Ignore KV elements in LAYOUT_LIST
