src/textractor.py
=> CLI typo fix

README.md
=> More info on the pricing

prettyprinter/textractprettyprinter/t_pretty_print_expense.py
Pretty printer module for Textract's new AnalyzeExpense API
=> Pretty printer module for Textract's new AnalyzeExpense API

src/trp.py
Customer was't able to us the original reading order logic for their PDF documents. The original logic would break when last of line of a paragraph happens to have the same length as other irrelevant parts in the same page, eg. a section heading, and would consider such line as part of the section header column.
An example of such issue:
The output text would be 
> Better lives for all Canadians with a myeloproliferative neoplasm (MPN)
> …
> Vision
> disorder.
Another issue is: a line being separated by Textract by mistake would result in multiple columns and would be printed out out-of-order. An example of such issue is below:
The output would be 
> The CADTH Canadian Drug Expert Committee (CDEC) recommends that halobetasol propionate …
=> - Modified logic to determine columns in getLinesInReadingOrder.

tpipelinegeofinder/textractgeofinder/tgeofinder.py, tpipelinegeofinder/textractgeofinder/tword.py
=> fix issue 59 add comparison

helper/bin/amazon-textract
=> Fix Stdin on amazon-textract command (issue 63)

prettyprinter/textractprettyprinter/t_pretty_print.py
Extend function of get_string function to consider also additional parameters based on the ouput_type
=> add parameters of get additional details

overlayer/README.md
update documentation with code samopel for PDF bpunding box drawing
=> add pdf code sample

caller/tests/test_caller.py, caller/textractcaller/t_call.py
=> fix 83 plus test

caller/tests/test_caller.py, caller/textractcaller/t_call.py
=> chore: added call_textract_expense function and test

caller/textractcaller/__init__.py
=> add export for call_textract_expense

prettyprinter/tests/test_pretty_print.py, prettyprinter/textractprettyprinter/t_pretty_print.py
=> fix: add more output to list

tpipelinegeofinder/tests/test_tgeofinder.py, tpipelinegeofinder/textractgeofinder/tgeofinder.py
*Issue:* #94, #92
*Description of changes:* 
1. add handling for of functions for multipage documents.
2. add depreciation warning for find_phrase_in_lines
=> extend multipage handling

helper/setup.py, overlayer/setup.py, tpipelinepagedimensions/setup.py
*Description of changes:* update to latest versions
=> upgrade version

src/trp.py
*Description of changes:* add page number to page class to simplefy the iteration for drawing bounding boxes and searches.
=> add page_no

caller/textractcaller/t_call.py
=> add check on force_sync_api

helper/bin/amazon-textract
=> fix: convert to array

textractor/parsers/response_parser.py
extending the list of word objects instead of assignment
Extend array instead of assignment. Not tested.
=> Fix bug for assignment of words to value fields

textractor/parsers/response_parser.py, textractor/textractor.py
*Issue #, if available:* Fixes #123
*Description of changes:* Fixes AnalyzeID words and lines not being added to the document object. 
=> Parse words and lines in AnalyzeID

textractor/parsers/response_parser.py
*Issue #, if available:* #122
*Description of changes:* Similar fix to AnalyzeID, parse Words and Lines to the page object for visualizations.
An upcoming PR will add expense specific visualization. 
=> Fix AnalyzeExpense visualization

caller/setup.py, helper/setup.py, prettyprinter/tests/test_pretty_print.py, prettyprinter/textractprettyprinter/t_pretty_print.py
fixes #148
updating the versions of caller, helper and prettyprinter to the latest
=> Fix Helper Lending Error

setup.py
=> Version 1.0.24

.github/workflows/lambda_layers.yml
*Issue #:* #174 
*Description of changes:* Add a new set of lambda layers that include pandas.
=> Add new lambda layer with pandas

requirements.txt
amazon-textract-response-parser==0.1.42
amazon-textract-caller==0.0.28
tabulate==0.9.*
=> upgrade requirement versions

textractor/textractor.py
=> fixing queries call in async mode

.github/workflows/lambda_layers.yml
*Issue #, if available:* #204
*Description of changes:* Adds 3 new actions to the lambda layer builder to support Python 3.10.
=> Add Python 3.10

caller/README.md, caller/tests/test_caller.py, caller/textractcaller/__init__.py, caller/textractcaller/t_call.py
Added support for Custom Queries within Textract Caller
https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-textract-custom-queries-information-extraction-business-specific-documents/
=> Added Textract Caller support for Custom Queries

overlayer/setup.py, tpipelinepagedimensions/setup.py
*Description of changes:* Bump pypdf version to address security concerns. 
=> Bump pypdf version

prettyprinter/textractprettyprinter/t_pretty_print_layout.py
*Issue #, if available:* resolves #263
*Description of changes:* Fixed the LAYOUT_FIGURE geo collection to be generated per page.
=> fix: resolved issue with multi-page figure text exclusion in Layout prettyprinter

textractor/entities/table.py, textractor/utils/geometry_util.py
*Description of changes:* Fixes table indexing and strip_headers.
Introduces a breaking change in table indexing which will be 0-indexed going forward. We will not release this under a new major version as in its previous state indexing did not work so it is safe to assume that no one depends on it.
=> Fix table post-processing

prettyprinter/textractprettyprinter/t_pretty_print_layout.py
Blazing fast linearization with LAYOUT and TABLES ⚡️⚡️
Single PDF 482 Pages with LAYOUT and TABLES - Textract  Time Taken: 00:05:22
Layout Linearizer - Time Taken: 00:00:01
Single PDF 100 Pages with LAYOUT and TABLES - Textract  Time Taken: 00:01:08
Layout Linearizer - Time Taken: 00:00:00 (almost negligible to register)
=> enhance: Performance improvements for LAYOUT prettyprinter

textractor/data/text_linearization_config.py, textractor/entities/expense_field.py, textractor/entities/key_value.py, textractor/entities/layout.py, textractor/entities/page.py, textractor/entities/page_layout.py, textractor/entities/signature.py, textractor/entities/table.py, textractor/parsers/response_parser.py, textractor/utils/geometry_util.py
*Issue #, if available:* N\A
*Description of changes:* Applied black to Textractor
=> Reformat with Black

prettyprinter/textractprettyprinter/t_pretty_print_layout.py
*Issue #, if available:* #284
*Description of changes:* Fixed with condition check to see if relationships exists.
=> fix: LAYOUT prettyprinter fix LAYOUT_FIGURE issue #284

textractor/entities/bbox.py, textractor/entities/selection_element.py, textractor/entities/table.py, textractor/entities/table_cell.py, textractor/entities/value.py, textractor/entities/word.py, textractor/parsers/response_parser.py
*Description of changes:* Fix issue where selection elements inside of tables were not properly sorted w.r.t their lines.
=> Fix selection elements in table

tests/test_get_text_and_words.py, textractor/entities/layout.py, textractor/entities/table.py, textractor/utils/text_utils.py
*Description of changes:* Fix prefix and suffix not being properly added in several cases.
=> Fix LAYOUT_TABLE prefix and suffix not being properly added

textractor/entities/table_title.py
*Description of changes:* Fix TableTitle `.get_text()` raising an exception.
=> Fix table title .get_text()

textractor/entities/table.py
*Description of changes:* Addresses and issue where empty column will cause `.to_pandas()` to raise an exception. 
=> Fix .to_pandas() raising an exception

docs/source/textractor.entities.rst
*Description of changes:* So entities were not in the official documentation, hurting discoverability. 
=> Add missing entities in docs

textractor/parsers/response_parser.py
*Description of changes:* In some cases the response when read from an S3 bucket can have EntityTypes set to `null` instead of `[]` or being absent. This PR handles the edge case gracefully.
=> Handle null EntityTypes

caller/textractcaller/t_call.py
Fixes issue #345 
Implemented a more robust S3 path parsing method to cover for path patterns reported in the issue.
=> Fixes issue #345 : S3 path parser

textractor/cli/cli.py, textractor/parsers/response_parser.py
*Description of changes:* Fix bug where a figure without children would be discard as an empty layout.
=> Fix missing figures

textractor/textractor.py
*Description of changes:* Updating the return type and function doc for `start_document_text_detection`. Language is copied from `start_document_analysis`.
=> Update function doc and return type

textractor/entities/lazy_document.py, textractor/textractor.py
*Issue #, if available:* #421
*Description of changes:* Remove s3_client instantiation in `_get_document_images_from_path`
=> Fix s3 client instantiation in _get_document_images_from_path
